import { PropsWithChildren } from "react";
import "@mantine/core/styles.css";
import "./globals.scss";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
};

export default RootLayout;
